version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: bizaway
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d
    restart: unless-stopped
